# Generated by Django 2.2.5 on 2019-09-11 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(editable=False, verbose_name='creation time')),
                ('modification_time', models.DateTimeField(default=None, editable=False, verbose_name='modification time')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='price')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='product.Product', verbose_name='cart items')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('creation_time', models.DateTimeField(editable=False, verbose_name='creation time')),
                ('modification_time', models.DateTimeField(default=None, editable=False, verbose_name='modification time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('payment_status', models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=16, null=True, verbose_name='Payment status')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('cancelled', 'Canceled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('declined', 'Declined'), ('no_response', 'No Response'), ('transit', 'Transit')], default='new', max_length=32, null=True, verbose_name='Order status')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.Cart', verbose_name='cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
