# Generated by Django 2.2.5 on 2019-09-11 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(editable=False, verbose_name='creation time')),
                ('modification_time', models.DateTimeField(default=datetime.datetime(2019, 9, 11, 13, 37, 39, 3442), editable=False, verbose_name='modification time')),
                ('credit', models.PositiveIntegerField(default=0)),
                ('lang', models.CharField(choices=[('fa', 'Farsi'), ('en', 'English')], default='fa', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['user'],
                'abstract': False,
            },
        ),
    ]
