# Generated by Django 2.2.5 on 2019-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='modification_time',
            field=models.DateTimeField(default=None, editable=False, verbose_name='modification time'),
        ),
    ]
