# Generated by Django 2.2.5 on 2019-09-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('simple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Simple')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=('core.simple',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(editable=False, verbose_name='creation time')),
                ('modification_time', models.DateTimeField(default=None, editable=False, verbose_name='modification time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('rate', models.CharField(choices=[('weak', 'Weak'), ('fine', 'Fine'), ('superb', 'Superb')], default='fine', max_length=40, verbose_name='rate')),
                ('stack', models.IntegerField(verbose_name='stack')),
                ('available', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='product.Category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'abstract': False,
            },
        ),
    ]
