# Generated by Django 2.2.5 on 2019-09-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('simple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Simple')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
            bases=('core.simple',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('simple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Simple')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='price')),
                ('rate', models.CharField(choices=[('weak', 'Weak'), ('fine', 'Fine'), ('superb', 'Superb')], default='fine', max_length=40, verbose_name='rate')),
                ('stack', models.IntegerField(verbose_name='stack')),
                ('available', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'abstract': False,
            },
            bases=('core.simple',),
        ),
    ]
