# Generated by Django 2.2.5 on 2019-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='None', max_length=40, verbose_name='name'),
        ),
    ]
