# Generated by Django 2.2.5 on 2019-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(editable=False, verbose_name='creation time')),
                ('modification_time', models.DateTimeField(default=None, editable=False, verbose_name='modification time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='English name')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='English description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
